language: cpp
compiler: gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi;
script: (cd build && make && make test)
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
sudo: false
branches:
  only:
  - master
